apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: telegram-bot
type: Opaque
stringData:
  BOT_TOKEN: "YOUR_BOT_TOKEN_HERE"
  POSTGRES_PASSWORD: "strongpassword"
  WEBHOOK_SECRET: "random_webhook_secret"